Repository hmcts/wa-task-batch-service, pull requests merged in 2023-10, with the labels that each got.

#158 RWA-2877: Helmet downgrade to 4.2
  package.json
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-158

#159 RWA-2845 Migrating to Workload Identity
  charts/wa-task-batch-service/Chart.yaml
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-159

#160 RWA-2882: Excluding helmet from auto upgrading by renovate
  .github/renovate.json
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-160
