Repository hmcts/wa-task-batch-service, pull requests merged in 2023-05, with the labels that each got.

#64 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-64

#57 RWA-2218-cleanUpSensitiveLogs job added
  src/main/model/job-names.ts
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-57

#65 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-65
