Repository hmcts/wa-task-batch-service, pull requests merged in 2023-01, with the labels that each got.

#48 RWA-2124 - axios 1.2.2, config 3.3.8 and tsconfig-paths 4.1.1
  package.json
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-48

#51 RWA-2186 removing deprecated code
  Jenkinsfile_CNP
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-51

#52 RWA-2191 Fix CVE problem of cookiejar
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-52

#50 RWA-2184 push back to config version 3.3.7
  .gitignore
  Jenkinsfile_nightly
  package.json
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-50
