Repository hmcts/wa-task-batch-service, pull requests merged in 2023-09, with the labels that each got.

#75 RWA-2761 security scan fix
  yarn-audit-known-issues
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-75

#84 RWA-2764 updated dependencies
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-84

#85 RWA-2744: Update Renovate Config
  .github/renovate.json
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-85

#102 RWA-2796: Renovate upgrades
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-102
