Repository hmcts/wa-task-batch-service, pull requests merged in 2024-04, with the labels that each got.

#362 RWA-3246: Remove Dependabot
  .dependabot/config.yml
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-362

#47 RWA-1695 - added unit tests
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  jest.config.js
  package.json
  src/test/unit/logger.test.ts
  src/test/unit/task-monitor-service.test.ts
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-47

#369 RWA-3301: Update formidable
  package.json
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-369
