Repository hmcts/wa-task-batch-service, pull requests merged in 2024-09, with the labels that each got.

#457 RWA-3735: Upgrade job to 2.1.2
  charts/wa-task-batch-service/Chart.yaml
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-457

#462 RWA-3808 - dependency updates
  package.json
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-462

#470 RWA-3823: Bump Versions
  package.json
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-470
