Repository hmcts/wa-task-batch-service, pull requests merged in 2025-06, with the labels that each got.

#575 RWA-4433: Resolved nightly CVE
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-575

#576 RWA-4337: Consolidate PRs
  package.json
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-576

#579 RWA-3328 changes
  .eslintignore
  .eslintrc.js
  eslint.config.js
  package.json
  src/test/unit/sample.ts
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-579
