Repository hmcts/wa-task-batch-service, pull requests merged in 2025-07, with the labels that each got.

#580 RWA-4469: Routes tests fix
  README.md
  src/test/routes/home.ts
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-580

#583 Revert "RWA-4469: Routes tests fix"
  README.md
  src/test/routes/home.ts
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-583

#585 RWA-4526: Upgrade superagent
  package.json
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-task-batch-service-pr-585
